### ISSUE TITLE
Question on how to use this package

### ISSUE THREAD

**Issue by herryswastika** [vrkansagara/LaraOutPress#17]
Hi, just a quick question on how to use this package. Do I need to set middleware, in what middleware? Do I need to add ->middleware('laraoutpress') in the route web.php ? Do I need to modify anything in app/http/kernel.php? etc etc. 
Thanks

**Comment by vrkansagara** [comment]
Hello can you follow the readme file first carefully ! And implement. If not works I will definitely will help !

**Comment by vrkansagara** [comment]
@herryswastika Hope this issue is solved !

**Comment by vrkansagara** [comment]
@herryswastika , It's look like you solved your problem so closing this issue!
