### ISSUE TITLE
dompdf with not working 

### ISSUE THREAD

**Issue by medhirajsharma** [vrkansagara/LaraOutPress#19]
dompdf with not working  and the return blank page 

Thank you

**Comment by vrkansagara** [comment]
@medhirajsharma Glade to hear from you. Can you share me bellow details.
Laravel version and Dompdf version.

**Comment by medhirajsharma** [comment]
Thank you
https://github.com/barryvdh/laravel-dompdf
![image](https://user-images.githubusercontent.com/21426954/58070111-72648c80-7bb5-11e9-8393-ad12d90f1b18.png)

my code 
`$pdf = app('dompdf.wrapper')->loadView('order-pdf', ['orders' => $orders, 'orders_details' => $orders_details]);

        if ($type == 'stream') {
            return $pdf->stream('invoice.pdf');
        }

        if ($type == 'download') {
            return $pdf->download('invoice.pdf');
        }`
if .env file `VRKANSAGARA_COMPRESS_ENABLED =false` then proper work

and if .env file `VRKANSAGARA_COMPRESS_ENABLED =true` then not work

sorry for my English

**Comment by cygnet-vrkansagara** [comment]
@medhirajsharma We need to skip some of the packages for avoiding such issue.

**Comment by vrkansagara** [comment]
@medhirajsharma  Can you explain more in details that what kind of problem are you facing?

**Comment by vrkansagara** [comment]
`dev-master` is ready to test. Would any one wanted to test this.

**Comment by vrkansagara** [comment]
Closing this issue against release of https://github.com/vrkansagara/LaraOutPress/tree/2.0.3
