### ISSUE TITLE
package name conflict ? 

### ISSUE THREAD

**Issue by fatihtoprak** [vrkansagara/LaraOutPress#21]
adresi gönderin beyler 😎

**Comment by vrkansagara** [comment]
@fatihtoprak Can you bit in english please?

**Comment by vrkansagara** [comment]
![Screenshot 2021-02-04 at 8 51 06 PM](https://user-images.githubusercontent.com/12006483/106914130-b6e9e000-672a-11eb-91c5-12d46f724b02.png)


@fatihtoprak  hum

**Comment by fatihtoprak** [comment]
ehheh its kind a funny one too. What a tag :) https://prnt.sc/ybtpb3

Anyway, the problem is righ on screenshot. Please fix the file name. 

https://prnt.sc/ybtr9i

**Comment by vrkansagara** [comment]
Noted with thanks

Let me fix and update you soon.

**Comment by vrkansagara** [comment]
@fatihtoprak This is fixed. Let me know if any.

**Comment by fatihtoprak** [comment]
Already done. Enjoy.
