### ISSUE TITLE
How to exclude some routes?

### ISSUE THREAD

**Issue by perffy** [vrkansagara/LaraOutPress#25]
Hi,

the package is the best for this purpose, unfortunately, I don't see if there is an option to exclude some routes to be excluded.
Unfortunately, it doesn't work with Laravel 8 and Livewire on my admin routes.

I see that you are planing in the future to add this option, but can you tell me some trick on how to bypass it?

Thanks

**Comment by cp-vrkansagara** [comment]
Hey Perffy, I am glade that you are using this package.

As of now you can make a copy of `AfterMiddleware.php` and use is as your own code till the next release do the fixes.

**Comment by perffy** [comment]
so i place the AfterMiddleware.php in my Middleware folder and add it to all routes where I want the code to be compressed?

**Comment by vrkansagara** [comment]
@perffy  This not as easy, Let me do work on this week and let you know for next release

**Comment by najathi** [comment]
I'm also facing the same problem

**Comment by vrkansagara** [comment]
https://github.com/vrkansagara/LaraOutPress/tree/dev-master is ready to fixing reported issue. any one wanted to test this code

**Comment by najathi** [comment]
// Is this library is enable or not.
    'enabled' => env('VRKANSAGARA_COMPRESS_ENABLED', false),

// Do we are debug the data
'debug' => env('VRKANSAGARA_COMPRESS_DEBUG', false),

// In which environment compression work.
'target_environment' => env('VRKANSAGARA_COMPRESS_ENVIRONMENT', ''),

 **_// Exclude routes from the compression
'exclude_routes' => [
    'api/*',
]_**

**Comment by vrkansagara** [comment]
@najathi  Is there anything missing or not working ?

**Comment by vrkansagara** [comment]
Closing this issue against release of https://github.com/vrkansagara/LaraOutPress/tree/2.0.3
