### ISSUE TITLE
[INFORMATION REQUEST] Is there a way to make this work only in Production?

### ISSUE THREAD

**Issue by iec989** [vrkansagara/LaraOutPress#7]
Thanks for this! The only one that actually worked for me as expected.

I however was wondering if I there is a way to execute the middleware only in Production?

**Comment by vrkansagara** [comment]
@iec989 I will add this features into this repo soon.

**Comment by vrkansagara** [comment]
Hello @iec989 This features added.

Fetch new release for that.

**Comment by vrkansagara** [comment]
@iec989  any comment on this!
